### ISSUE TITLE
Different Register

### ISSUE THREAD

**Issue by rainer1370** [KIT-IBPT/epics-mrf#1]
According to the [EVR Manual](www.mrf.fi/dmdocuments/EVR-MRM-007.pdf
), the CGLOCK bit is at 0x052, bit 9, not 0x0050[9] as seen on line 551 of <evr-common.inc.db>.  Maybe I'm missing something?

Thanks,
-R

https://github.com/KIT-IBPT/epics-mrf/blob/46051931017f9559052fb1251cf11ed87f5cbd22/mrfApp/Db/evr-common.inc.db#L551

**Comment by smarsching** [comment]
No, the address is correct. Have a closer look at the manual: The dword that stores this bit starts at address 0x50. The byte containing bit 9 is indeed at address 0x052, but as the communication is done in full 32-bit words, the start address of the word is correct.

**Comment by rainer1370** [comment]
Ah! Makes much more sense. Thanks! I'm at NSLS 2 and looking into using a driver like this. I'll keep you posted.

-R

--
Rob Rainer
NSLS-II Controls Engineer

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
